name: ci workflow
on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Setup Go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: 1.22
            
            - name: Build the product-catalog service
              run: |
                  cd src/product-catalog
                  go mod download
                  go build -o product-catalog src/product-catalog/main.go

            - name: run unit test
              run: |
                  cd src/product-catalog
                  go test src/product-catalog/..
    
    code-quality:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout Code
             uses: actions/checkout@v4
             with:
              fetch-depth: 0

           - name: Run golang lint
             uses: golangci/golangci-lint-action@v8

    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Install Docker
              uses: docker/setup-docker@v4

            - name: Login to Docker
              uses: docker/login-action@v2
              with:
                registry: docker.io
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD}}

            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                 context: src/product-catalog
                 file: Dockerfile
                 push: true
                 tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog/${{ github.run_id }}


    Updae-k8s:
        runs-on: ubuntu-latest
        needs: docker
        steps:
         - name: Checkout Code
           uses: actions/checkout@v4
           with:
            token: ${{ secrets.GITHUB_TOKEN }}

         - name: Update tag in K8 manifest
           run: |
            sed -i 's/image: .*tag/${{ secrets.DOCKER_USERNAME }}/product-catalog/${{github.run.id }}

         - name: Git commit & Push
           run: |
            git config --global user.email "niketakulshrestha2026@gmail.com"
            git config --global user.name "Niketa"
            git add .
            git commit -m "[CI]: uPDATE PRODUCT CATALOG SERVICE TAG"
            git push origin HEAD:main -f
           
    

         
              

       
        
        
              



    

            

